import { join } from "path";

export const CONFIG_DIRECTORY_DEFAULT_NAME = '.run-the-sheet';
export const CONFIG_DIRECTORY_DEFAULT_LOCATION_PARENT_PATH = process.env.HOME as string;
export const CONFIG_DIRECTORY_DEFAULT_PATH = join(CONFIG_DIRECTORY_DEFAULT_LOCATION_PARENT_PATH, CONFIG_DIRECTORY_DEFAULT_NAME);
